services:
  postgres:
    image: postgres:16-alpine
    container_name: yelpcamp-db
    environment:
      POSTGRES_USER: yelpcamp
      POSTGRES_PASSWORD: yelpcamp123
      POSTGRES_DB: yelpcamp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
